let diagrams=[];let current=0;let selected=new Set();let route=[];
const fan=document.getElementById('fan');const sectorButtons=document.getElementById('sectorButtons');
const diagramId=document.getElementById('diagramId');const diagramTitle=document.getElementById('diagramTitle');const diagramDesc=document.getElementById('diagramDesc');const progress=document.getElementById('progress');const routeList=document.getElementById('routeList');const reportView=document.getElementById('reportView');
function degToRad(d){return d*Math.PI/180}function pt(cx,cy,r,a){return [cx+r*Math.cos(degToRad(a)),cy-r*Math.sin(degToRad(a))]}function pathSector(cx,cy,r0,r1,a0,a1){const [x1,y1]=pt(cx,cy,r1,a0),[x2,y2]=pt(cx,cy,r1,a1),[x3,y3]=pt(cx,cy,r0,a1),[x4,y4]=pt(cx,cy,r0,a0);const large=(a1-a0)>180?1:0;return `M ${x1} ${y1} A ${r1} ${r1} 0 ${large} 0 ${x2} ${y2} L ${x3} ${y3} A ${r0} ${r0} 0 ${large} 1 ${x4} ${y4} Z`}
function textAttrs(mid,cx,cy,r){const [x,y]=pt(cx,cy,r,mid);let rot=90-mid;let anchor='start'; if(mid>90){rot=270-mid;anchor='end'} return {x,y,rot,anchor}}
function render(){const d=diagrams[current];selected.clear();reportView.classList.add('hidden');diagramId.textContent=d.id;diagramTitle.textContent=d.title;diagramDesc.textContent=d.description||'';progress.textContent=`${current+1} / ${diagrams.length}`;drawFan(d);drawButtons(d);drawRoute()}
function drawFan(d){const n=d.sectors.length;const W=1000,H=520,cx=500,cy=470,r0=58,r1=430;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${d.title}">`;svg+=`<path class="outer-arc" d="M ${cx-r1} ${cy} A ${r1} ${r1} 0 0 1 ${cx+r1} ${cy}"/>`;for(let i=0;i<n;i++){const a0=180-(i+1)*180/n;const a1=180-i*180/n;const mid=(a0+a1)/2;svg+=`<path class="sector-path" data-i="${i}" d="${pathSector(cx,cy,r0,r1,a0,a1)}"></path>`;const ta=textAttrs(mid,cx,cy,r1-62);const label=`${i+1}. ${d.sectors[i]}`;svg+=`<text class="sector-text" x="${ta.x}" y="${ta.y}" text-anchor="${ta.anchor}" transform="rotate(${ta.rot} ${ta.x} ${ta.y})">${escapeHtml(label)}</text>`;const na=textAttrs(mid,cx,cy,r1-20);svg+=`<text class="sector-num" x="${na.x}" y="${na.y}" text-anchor="middle">${i+1}</text>`}svg+=`<circle class="center-dot" cx="${cx}" cy="${cy}" r="10"/><path class="outer-arc" d="M ${cx-r0} ${cy} A ${r0} ${r0} 0 0 1 ${cx+r0} ${cy}"/></svg>`;fan.innerHTML=svg;fan.querySelectorAll('.sector-path').forEach(p=>{p.addEventListener('click',()=>toggle(Number(p.dataset.i)))});}
function drawButtons(d){sectorButtons.innerHTML='';d.sectors.forEach((s,i)=>{const b=document.createElement('button');b.className='sector-btn';b.textContent=`${i+1}. ${s}`;b.onclick=()=>toggle(i);sectorButtons.appendChild(b)})}
function toggle(i){const d=diagrams[current];if(!d.multi){selected.clear()} if(selected.has(i))selected.delete(i);else selected.add(i);fan.querySelectorAll('.sector-path').forEach((p,idx)=>p.classList.toggle('selected',selected.has(idx)));sectorButtons.querySelectorAll('.sector-btn').forEach((b,idx)=>b.classList.toggle('selected',selected.has(idx)))}
function next(){saveStep(); if(current<diagrams.length-1){current++;render()}else finish()}
function back(){if(current>0){current--;render()}}
function saveStep(){const d=diagrams[current];const answers=[...selected].sort((a,b)=>a-b).map(i=>d.sectors[i]);if(answers.length){route.push({id:d.id,title:d.title,answers})}}
function finish(){saveStep();const name=document.getElementById('clientName').value||'Не указано';const req=document.getElementById('clientRequest').value||'Не указан';let txt=`ЗАКЛЮЧЕНИЕ ATLAS CORE\n\nКлиент: ${name}\nЗапрос: ${req}\nДата: ${new Date().toLocaleString('ru-RU')}\n\nКРАТКИЙ ВЫВОД\nДиагностика проведена по маршруту маятника. Ниже указаны выбранные сектора и основная логика для дальнейшей интерпретации.\n\nВЫБРАННЫЕ СЕКТОРА\n`;route.forEach((r,k)=>{txt+=`\n${k+1}. ${r.id} — ${r.title}\n   ${r.answers.join(', ')}\n`});txt+=`\nПРАКТИЧЕСКИЙ ПЛАН\n1. Выделить 1–3 повторяющиеся темы.\n2. Определить главный уровень причины.\n3. Выбрать одну практику или действие на 7 дней.\n4. Провести повторную диагностику после выбранного срока.\n\nПримечание: отчет является консультационным инструментом и не заменяет медицинские, юридические или финансовые решения специалистов.`;reportView.textContent=txt;reportView.classList.remove('hidden');drawRoute()}
function drawRoute(){routeList.innerHTML='';route.forEach((r)=>{const div=document.createElement('div');div.className='route-item';div.innerHTML=`<b>${r.id} ${escapeHtml(r.title)}</b>${escapeHtml(r.answers.join(', '))}`;routeList.appendChild(div)})}
function resetAll(){current=0;route=[];selected.clear();render()}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
document.getElementById('nextBtn').onclick=next;document.getElementById('backBtn').onclick=back;document.getElementById('finishBtn').onclick=finish;document.getElementById('newBtn').onclick=resetAll;document.getElementById('reportBtn').onclick=finish;
async function init(){try{const res=await fetch('data/diagrams.json',{cache:'no-store'});diagrams=await res.json()}catch(e){diagrams=[{"id":"D001","title":"Главное меню диагностики","description":"Резервная диаграмма.","multi":true,"sectors":["Человек","Финансы","Бизнес","Причина","Энергия","Род","Практики","Завершить"]}]}render();if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{})}}
init();
